# Generated by Django 5.0.6 on 2024-06-29 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('dashboard', '0002_alter_schoolteam_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(blank=True, choices=[('Group', 'Group'), ('Knockout', 'Knockout')], max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('InPlay', 'InPlay'), ('Complete', 'Complete'), ('Postponed', 'Postponed')], default='Pending', max_length=100, null=True)),
                ('round', models.CharField(blank=True, max_length=100, null=True)),
                ('venue', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('team1_score', models.IntegerField(blank=True, null=True)),
                ('team2_score', models.IntegerField(blank=True, null=True)),
                ('team1_sets_won', models.IntegerField(blank=True, default=0, null=True)),
                ('team2_sets_won', models.IntegerField(blank=True, default=0, null=True)),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volfix', to='dashboard.season')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vteam1', to='dashboard.schoolteam')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vteam2', to='dashboard.schoolteam')),
            ],
            options={
                'verbose_name': 'Fixture',
                'verbose_name_plural': 'Fixtures',
            },
        ),
        migrations.CreateModel(
            name='match_official',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_role', models.CharField(blank=True, choices=[('Referee', 'Referee'), ('Umpire', 'Umpire'), ('First assistant', 'First assistant '), ('Second assistant', 'Second assistant '), ('4th Official', '4th Official')], max_length=100, null=True)),
                ('fixture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vofix', to='volleyball.fixture')),
                ('official', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vofficial', to='dashboard.official')),
            ],
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('Serve', 'Serve'), ('Ace', 'Ace'), ('Block', 'Block'), ('Attack', 'Attack'), ('Kill', 'Kill'), ('Dig', 'Dig'), ('Set', 'Set'), ('Substitution', 'Substitution'), ('Timeout', 'Timeout'), ('Injury', 'Injury'), ('Service Error', 'Service Error'), ('Attack Error', 'Attack Error'), ('Blocking Error', 'Blocking Error'), ('Ball Handling Error', 'Ball Handling Error')], max_length=20)),
                ('minute', models.IntegerField()),
                ('commentary', models.TextField(blank=True, null=True)),
                ('athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vathlete', to='accounts.athlete')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volleyball.fixture')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vteam', to='dashboard.schoolteam')),
            ],
        ),
        migrations.CreateModel(
            name='VGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('teams', models.ManyToManyField(to='dashboard.schoolteam')),
            ],
        ),
        migrations.AddField(
            model_name='fixture',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='volleyball.vgroup'),
        ),
        migrations.CreateModel(
            name='Volleyball',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'male'), ('Female', 'female')], max_length=10, null=True)),
                ('age', models.CharField(blank=True, choices=[('U16', 'U16'), ('U18', 'U18'), ('U20', 'U20')], max_length=50, null=True)),
                ('participants', models.IntegerField()),
                ('number_of_groups', models.IntegerField()),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volchamp', to='accounts.championship')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volseason', to='dashboard.season')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volsport', to='accounts.sport')),
                ('teams', models.ManyToManyField(to='dashboard.schoolteam')),
            ],
        ),
        migrations.AddField(
            model_name='vgroup',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volgroup', to='volleyball.volleyball'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='volleyball.volleyball'),
        ),
    ]
