# Generated by Django 5.0.6 on 2024-07-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volleyball', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='stage',
            field=models.CharField(blank=True, choices=[('Group', 'Group'), ('Knockout', 'Knockout'), ('Classification', 'Classification')], max_length=100, null=True),
        ),
    ]
