# Generated by Django 5.0.6 on 2024-08-09 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_schoolteam_gender'),
        ('volleyball', '0002_alter_fixture_stage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fixture',
            new_name='VFixture',
        ),
    ]
