# Generated by Django 5.0.6 on 2024-07-27 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rugby7s', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='r7group',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r7group', to='rugby7s.rugby7s'),
        ),
    ]
