# Generated by Django 5.0.6 on 2024-06-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netball', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='netball',
            name='age',
            field=models.CharField(blank=True, choices=[('U16', 'U16'), ('U18', 'U18'), ('U20', 'U20')], max_length=50, null=True),
        ),
    ]
