# Generated by Django 5.0.6 on 2024-06-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athleticsevent',
            old_name='team',
            new_name='teams',
        ),
        migrations.AddField(
            model_name='athleticsevent',
            name='age',
            field=models.CharField(blank=True, choices=[('U16', 'U16'), ('U18', 'U18'), ('U20', 'U20')], max_length=10, null=True),
        ),
    ]
