# Generated by Django 5.0.6 on 2024-06-28 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='football',
            name='age',
            field=models.CharField(blank=True, choices=[('U16', 'U16'), ('U18', 'U18'), ('U20', 'U20')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='football',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
    ]
