# Generated by Django 5.0.6 on 2024-07-25 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_football_age_alter_football_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Standings',
        ),
    ]
