# Generated by Django 5.0.6 on 2024-07-31 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('basketball5', '0001_initial'),
        ('dashboard', '0002_alter_schoolteam_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='b3group',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='b3group',
            name='teams',
        ),
        migrations.RemoveField(
            model_name='basketball3',
            name='championship',
        ),
        migrations.RemoveField(
            model_name='basketball3',
            name='season',
        ),
        migrations.RemoveField(
            model_name='basketball3',
            name='sport',
        ),
        migrations.RemoveField(
            model_name='basketball3',
            name='teams',
        ),
        migrations.AlterField(
            model_name='match_official',
            name='official',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b5officicial', to='dashboard.official'),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='athlete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b5athlete', to='accounts.athlete'),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket5_team', to='dashboard.schoolteam'),
        ),
        migrations.CreateModel(
            name='B5Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(blank=True, choices=[('Group', 'Group'), ('Knockout', 'Knockout')], max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('InPlay', 'InPlay'), ('Complete', 'Complete'), ('Postponed', 'Postponed')], default='Pending', max_length=100, null=True)),
                ('round', models.CharField(blank=True, max_length=100, null=True)),
                ('venue', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('team1_score', models.IntegerField(blank=True, null=True)),
                ('team2_score', models.IntegerField(blank=True, null=True)),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.season')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b5team1', to='dashboard.schoolteam')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b5team2', to='dashboard.schoolteam')),
            ],
        ),
        migrations.AlterField(
            model_name='match_official',
            name='fixture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b5fixture', to='basketball5.b5fixture'),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basketfixture', to='basketball5.b5fixture'),
        ),
        migrations.CreateModel(
            name='B5Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('teams', models.ManyToManyField(to='dashboard.schoolteam')),
            ],
        ),
        migrations.AddField(
            model_name='b5fixture',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b5group', to='basketball5.b5group'),
        ),
        migrations.CreateModel(
            name='Basketball5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.CharField(blank=True, choices=[('U16', 'U16'), ('U18', 'U18'), ('U20', 'U20')], max_length=50, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'male'), ('Female', 'female')], max_length=10, null=True)),
                ('participants', models.IntegerField()),
                ('number_of_groups', models.IntegerField()),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basketball5', to='accounts.championship')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basketball5', to='dashboard.season')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basketball5', to='accounts.sport')),
                ('teams', models.ManyToManyField(to='dashboard.schoolteam')),
            ],
        ),
        migrations.AddField(
            model_name='b5group',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b5comp', to='basketball5.basketball5'),
        ),
        migrations.AddField(
            model_name='b5fixture',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b5tourn', to='basketball5.basketball5'),
        ),
        migrations.DeleteModel(
            name='B3Fixture',
        ),
        migrations.DeleteModel(
            name='B3Group',
        ),
        migrations.DeleteModel(
            name='Basketball3',
        ),
    ]
