# Generated by Django 5.0.6 on 2024-06-29 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('dashboard', '0002_alter_schoolteam_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handball',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'male'), ('Female', 'female')], max_length=10, null=True)),
                ('age', models.CharField(blank=True, choices=[('U16', 'U16'), ('U18', 'U18'), ('U20', 'U20')], max_length=50, null=True)),
                ('participants', models.IntegerField()),
                ('number_of_groups', models.IntegerField()),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handchamp', to='accounts.championship')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handseason', to='dashboard.season')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handsport', to='accounts.sport')),
                ('teams', models.ManyToManyField(to='dashboard.schoolteam')),
            ],
        ),
        migrations.CreateModel(
            name='HGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handgroup', to='handball.handball')),
                ('teams', models.ManyToManyField(to='dashboard.schoolteam')),
            ],
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(blank=True, choices=[('Group', 'Group'), ('Knockout', 'Knockout')], max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('InPlay', 'InPlay'), ('Complete', 'Complete'), ('Postponed', 'Postponed')], default='Pending', max_length=100, null=True)),
                ('round', models.CharField(blank=True, max_length=100, null=True)),
                ('venue', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('team1_score', models.IntegerField(blank=True, null=True)),
                ('team2_score', models.IntegerField(blank=True, null=True)),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handfix', to='dashboard.season')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hteam1', to='dashboard.schoolteam')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hteam2', to='dashboard.schoolteam')),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='handball.handball')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='handball.hgroup')),
            ],
        ),
        migrations.CreateModel(
            name='match_official',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_role', models.CharField(blank=True, choices=[('Referee', 'Referee'), ('Umpire', 'Umpire'), ('First assistant', 'First assistant '), ('Second assistant', 'Second assistant '), ('4th Official', '4th Official')], max_length=100, null=True)),
                ('fixture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hofix', to='handball.fixture')),
                ('official', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hofficial', to='dashboard.official')),
            ],
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('Goal', 'Goal'), ('Save', 'Save'), ('Assist', 'Assist'), ('Penalty Goal', 'Penalty Goal'), ('Penalty Miss', 'Penalty Miss'), ('Yellow Card', 'Yellow Card'), ('Red Card', 'Red Card'), ('Suspension', 'Suspension'), ('Timeout', 'Timeout'), ('Substitution', 'Substitution'), ('Injury', 'Injury'), ('Fast Break', 'Fast Break'), ('Turnover', 'Turnover'), ('Interception', 'Interception'), ('Block', 'Block'), ('Foul', 'Foul'), ('Technical Foul', 'Technical Foul'), ('Offensive Foul', 'Offensive Foul'), ('Defensive Foul', 'Defensive Foul'), ('Dribbling Violation', 'Dribbling Violation'), ('Steps Violation', 'Steps Violation'), ('Passive Play', 'Passive Play'), ('Goalkeeper Save', 'Goalkeeper Save'), ('7-Meter Throw', '7-Meter Throw')], max_length=20)),
                ('minute', models.IntegerField()),
                ('commentary', models.TextField(blank=True, null=True)),
                ('athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hathlete', to='accounts.athlete')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handball.fixture')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hteam', to='dashboard.schoolteam')),
            ],
        ),
    ]
