# Generated by Django 5.0.6 on 2024-07-22 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_schoolteam_gender'),
        ('handball', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fixture',
            new_name='HFixture',
        ),
    ]
