# Generated by Django 5.0.6 on 2024-06-29 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('dashboard', '0002_alter_schoolteam_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basketball3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.CharField(blank=True, choices=[('U16', 'U16'), ('U18', 'U18'), ('U20', 'U20')], max_length=50, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'male'), ('Female', 'female')], max_length=10, null=True)),
                ('participants', models.IntegerField()),
                ('number_of_groups', models.IntegerField()),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basketball3', to='accounts.championship')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basketball3', to='dashboard.season')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basketball3', to='accounts.sport')),
                ('teams', models.ManyToManyField(to='dashboard.schoolteam')),
            ],
        ),
        migrations.CreateModel(
            name='B3Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('teams', models.ManyToManyField(to='dashboard.schoolteam')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b3comp', to='basketball3.basketball3')),
            ],
        ),
        migrations.CreateModel(
            name='B3Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(blank=True, choices=[('Group', 'Group'), ('Knockout', 'Knockout')], max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('InPlay', 'InPlay'), ('Complete', 'Complete'), ('Postponed', 'Postponed')], default='Pending', max_length=100, null=True)),
                ('round', models.CharField(blank=True, max_length=100, null=True)),
                ('venue', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('team1_score', models.IntegerField(blank=True, null=True)),
                ('team2_score', models.IntegerField(blank=True, null=True)),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.season')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b3team1', to='dashboard.schoolteam')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b3team2', to='dashboard.schoolteam')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b3group', to='basketball3.b3group')),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b3tourn', to='basketball3.basketball3')),
            ],
        ),
        migrations.CreateModel(
            name='match_official',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_role', models.CharField(blank=True, choices=[('Referee', 'Referee'), ('Umpire', 'Umpire'), ('First assistant', 'First assistant '), ('Second assistant', 'Second assistant '), ('4th Official', '4th Official')], max_length=100, null=True)),
                ('fixture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b3fixture', to='basketball3.b3fixture')),
                ('official', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b3officicial', to='dashboard.official')),
            ],
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('1-Pointer', '1-Pointer'), ('2-Pointer', '2-Pointer'), ('Inbound Pass', 'Inbound Pass'), ('Foul', 'Foul'), ('rebound', 'rebound'), ('steal', 'steal'), ('turnover', 'turnover'), ('Assist', 'Assist'), ('3-Pointer', '3-Pointer'), ('Block', 'Block'), ('Substitution', 'Substitution'), ('Shot Made (3-Pointer)', 'Shot Made (3-Pointer)'), ('Shot Missed (3-Pointer)', 'Shot Missed (3-Pointer)'), ('Free Throw', 'Free Throw')], max_length=25)),
                ('minute', models.IntegerField()),
                ('commentary', models.TextField(blank=True, null=True)),
                ('athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b3athlete', to='accounts.athlete')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basketfixture', to='basketball3.b3fixture')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_team', to='dashboard.schoolteam')),
            ],
        ),
    ]
